{
    'name': 'Hire Purchase System',
    'version': '1.1',
    'sequence': 1,
    'module_type': 'official',
    'summary': 'Customization for Hire Purchase',
    'author': 'GeoIworks',
    'images': [],
    'depends': [
        'base_setup',
        'web',
        'base', 
        'contacts',
        'account',
        'stock',
        'mail'
    ],
    'data': [
        # 'security/groups.xml',
        'security/ir.model.access.csv',
        'views/customer_statement_report.xml',
        'views/modify_menuitems.xml',
        'views/login_template.xml',
        'views/hubtel_webhook.xml',
        'views/res_config_settings_views.xml',
        'views/payment_notifications.xml',
        'views/nuovopay_lock_views.xml',
        'data/ir_cron.xml',
        'data/ir_sequence_data.xml',
        'views/favicon_template.xml',
        'views/product_page_template.xml',
        'views/product_details_template.xml',
        'views/product_template_inherit.xml',
        'views/home.xml',
        'views/res_user_inherit.xml',
        'views/res_partner.xml',
        'views/oppo_lock_views.xml',
        # 'views/settings_inherit.xml'
    ],
    'installable': True,
    'application': True,
    'assets': {
        'web.assets_frontend': [
            'gobtechnologies/static/src/scss/custom_styles.scss',
            'gobtechnologies/static/src/js/static/src/js/change_title.js',
            'gobtechnologies/static/src/js/static/src/js/nuovo_pay.js',
            'gobtechnologies/static/src/js/static/src/js/oppo_lock.js',
            'gobtechnologies/static/src/xml/nuovo_pay.xml',
            'gobtechnologies/static/src/xml/oppo_lock.xml',
            'gobtechnologies/static/src/js/static/src/js/dashboard/dashboard.js',
            'gobtechnologies/static/src/xml/dashboard/dashboard.xml',
            'gobtechnologies/static/src/js/static/src/js/dashboard/user_management.js',
            'gobtechnologies/static/src/xml/dashboard/user_management.xml',
            'gobtechnologies/static/src/js/static/src/js/dashboard/customer_management.js',
            'gobtechnologies/static/src/xml/dashboard/customer_management.xml',
            'gobtechnologies/static/src/js/static/src/js/dashboard/stock_management.js',
            'gobtechnologies/static/src/xml/dashboard/stock_management.xml',
            'gobtechnologies/static/src/js/static/src/js/dashboard/auditing.js',
            'gobtechnologies/static/src/xml/dashboard/auditing.xml',
            'gobtechnologies/static/src/js/static/src/js/dashboard/reports.js',
            'gobtechnologies/static/src/xml/dashboard/reports.xml',
        ],
        'web.assets_backend': [
            'gobtechnologies/static/src/scss/custom_styles.scss',
            'gobtechnologies/static/src/js/static/src/js/hubtel_notification_systray.js',
            'gobtechnologies/static/src/xml/hubtel_notification_systray.xml',
            'gobtechnologies/static/src/js/static/src/js/change_title.js',
            'gobtechnologies/static/src/js/static/src/js/nuovo_pay.js',
            'gobtechnologies/static/src/js/static/src/js/oppo_lock.js',
            'gobtechnologies/static/src/xml/nuovo_pay.xml',
            'gobtechnologies/static/src/xml/oppo_lock.xml',
            'gobtechnologies/static/src/js/static/src/js/dashboard/dashboard.js',
            'gobtechnologies/static/src/xml/dashboard/dashboard.xml',
            'gobtechnologies/static/src/js/static/src/js/dashboard/user_management.js',
            'gobtechnologies/static/src/xml/dashboard/user_management.xml',
            'gobtechnologies/static/src/js/static/src/js/dashboard/customer_management.js',
            'gobtechnologies/static/src/xml/dashboard/customer_management.xml',
            'gobtechnologies/static/src/js/static/src/js/dashboard/stock_management.js',
            'gobtechnologies/static/src/xml/dashboard/stock_management.xml',
            'gobtechnologies/static/src/js/static/src/js/dashboard/auditing.js',
            'gobtechnologies/static/src/xml/dashboard/auditing.xml',
            'gobtechnologies/static/src/js/static/src/js/dashboard/reports.js',
            'gobtechnologies/static/src/xml/dashboard/reports.xml',
        ],
    },
    'license': 'LGPL-3',
}
